### ISSUE TITLE
Research on how to prune graphnode

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1141]

**Comment by jay-kim-kor** [comment]
There are 2 way to prune data from DB. First, set `GRAPH_ETHEREUM_CLEANUP_BLOCKS` in env is prune cached block. But system may slow down by download repeatedly block.

Second way is delete row manually, [according maintainer](https://github.com/graphprotocol/graph-node/issues/2789#issuecomment-994130427), we can delete row manually but they recommended shutdown graphnode temporarily during remove old data.

So, I'll try second way. Because I think we might be needed cached block.

**Comment by jay-kim-kor** [comment]
The Graph Node seems it should have all historical data.
