### ISSUE TITLE
Load chainId and JSON-RPC interval from DB rather than define them within code

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#1252]

**Comment by nick-bisonai** [comment]
@martinkersner 
I believe this issue was raised since old fetcher had json rpc defined hardcoded inside code

in offchain aggregator fetcher,

primary json rpc is defined from .env and chain Id is loaded from the primary json rpc.
fallback json rpcs are utilized once added into db.

it is not hardcoded inside the code as in current fetcher. can this issue be closed?

**Comment by martinkersner** [comment]
Yes, you are right! We can close it 🦬
