### ISSUE TITLE
Fix high severity issue in `Aggregator.widthdrawFunds()`

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#357]

**Comment by KelvinThai** [comment]
Long story short: 
1. slither found a reentrancy pattern in aggregator.withdrawfunds() where state variable is updated before transfer
```
 updateAvailableFunds();
        (bool sent, ) = _recipient.call{value: _amount}("");
        if (!sent) {
            revert InsufficientBalance();
        }
```
2. However if we look into updateAvailableFunds(): the state is updated only when there are changes to `nowAvailable`. So in this case, the balance need to change first before calling updateAvailableFunds()
```
if (funds.available != nowAvailable) {
            recordedFunds.available = nowAvailable;
            emit AvailableFundsUpdated(nowAvailable);
        }
```
3. This function also comes with onlyOwner() modifier, so reentrency is nearly impossible, since the attacker contract must have Owner role.

I suggest we leave it as it is.

**Comment by KelvinThai** [comment]
Can we close this now?

**Comment by martinkersner** [comment]
@KelvinThai Yes, the function was removed in latest PR.
