### ISSUE TITLE
Separate counter for direct payment and prepayment acount

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl#364]

**Comment by KelvinThai** [comment]
I think if this is just for frontend presentation, we should not handle this in prepayment contract, since the accID is attatched to many operations. My suggestions:
1. We can edit the prepayment subgraph to handle `AccountCreated` event. If we find the account is created by VRFCoordinator, we don't save them.
2. we just filter from frontend, exclude any AccID which has VRFCoordinator as owner

**Comment by martinkersner** [comment]
@KelvinThai Sounds nice!

If I understand correctly, we will add the information about type of account (`temporary`, `regular`) to `AccountCreated` event and then filter within the subgraph. I agree with this suggestion.

However, we also need to consider our admin part, we should have understanding of what accounts are `temporary` and what account are `regular` so we can do some analysis on them when needed. We could always try to access the data collected by subgraph, but then we also need to create some interface to access it and it can be quite unnecessarily lengthy process. At best, we could access it through smart contract directly. Do you have any idea for this problem?

**Comment by KelvinThai** [comment]
humh! let me think about it. I'll implement to Account type for now
