### ISSUE TITLE
Finalize second fulfillment logic for RR operator

### ISSUE THREAD

**Issue by KelvinThai** [Bisonai/orakl#416]
For now: the operator who calls the fulfill function first will fulfill the request and get paid. Other operator will fail the fulfill transactions. Like a FCFS pattern

**Comment by KelvinThai** [comment]
My proposal:
+ We need to check the requestID, if that is already fulfilled, the operator should not fulfill it.
+ This should be implemented in the RR worker
+ We should put a warning in the docs, that the fullfill for RR request can be failed. In case the fulfill happens in the middle of worker checking for fulfilledID.

Reason:
From a consumer perspective: they're happy to know that every operator is racing to fulfill their request
From an operator perspective: they always need to enhance their infra(stable RPC, connections,...)
At the start there should not be many operators for RR.
We don't need to edit smart contracts, as we decided not to do onchain aggregation.

**Comment by martinkersner** [comment]
@KelvinThai Thank you! So you think we should not create a logic for a fulfillments from various node operators?

My idea was that consumer can ask for N responses where N is the current max number of off-chain node operators. Node operators start submitting the answers, and when it is larger than N, it will aggregate and fulfill consumer's callback. After receiving N submissions, no more submissions are accepted.

Node operators whose submission are accepted will be rewarded based on the response time arrival. At first, we would have just 1 response, then it could scale more.

**Comment by KelvinThai** [comment]
Aha! In that case, we need to change the smart contract for onchain aggregation.
That would bring some complication to it: how do we aggregate onchain data? we pick randomly or we normalize all results
If we have 1 operator, that one will fullfill all the responses in the response array. that's a bit weird. I consider we will have 1 operator for a while.
Both cases, we will need to edit onchain and offchain.

**Comment by martinkersner** [comment]
Off-chain modification will be just minimal, making sure we do not submit unless it is still allowed. On-chain changes can be quite big. The aggregation can be similar to what we do with `Aggregator`. One node operator cannot submit multiple responses, and consumer cannot ask for more responses than there are operators.

**Comment by KelvinThai** [comment]
Sounds good! If this logic is finalized, I can create issues and refactor both onchain and offchain.

**Comment by KelvinThai** [comment]
I've been thinking about this approach. Here are the questions that we need to answer before proceeding:
1. In case 3 registered oracle, but only 1 is up and running. The consumer asks for 3 submissions, then only 1 operator will submit all 3.  In that case, we need to edit the comeback submission mechanism in off-chain oracle, it will slow down the whole process.
2. In case we have 3 submissions from 3 operators, who would call the fulfill function?
3. How do we calculate the payment for the 3 submissions from 3 operators?

**Comment by martinkersner** [comment]
The first raised issue is very good one, and actually difficult for us to solve nicely because of the **lack of punishment mechanism**.

The simple solutions could be:
* Not our problem. It should be node operators goal to make more money by submitting requested data. Incentivisation by payment to node operators. If people want to make sure they get response they would select smaller number of responses. Currently, with chainlink you don't know who responded and how.
* Moving responsibility on consumer. We could split the response to 2 steps: 1) request for N responses 2) consumer computes aggregation of results in separate transaction.

For the questions:
2. The last submission would call the fulfill function.
3. My first idea was to make exponentially decreasing payment for each submission, but now I feel like linearly decreasing would be probably better, or maybe even equal proportion for all submissions.

**Comment by KelvinThai** [comment]
I think we should move on with an equal proportion for every submission. The last one to submit the data will call the fulfill function

**Comment by martinkersner** [comment]
Agree!
