### ISSUE TITLE
Read `VRF` and `RR` Requests form latest know listener state

### ISSUE THREAD

**Issue by bayram98** [Bisonai/orakl#826]
When are launch off-chain, we are missing the events which happened after the latest record. It would be good to check all the events we are missing and request to fulfill the request.

**Comment by nick-bisonai** [comment]
@Intizar-T will block storing into db will solve this issue? if so, please connect this issue with the pr.

**Comment by Intizar-T** [comment]
yes storing block in the db solves this issue because a block record will be deleted from db after all the events from that block are processed. So if we restart the server while it's processing a certain block, the restarted server will reprocess the same block because the block will still be in the db indicating it hasn't been fully/properly processed
